apiVersion: v1
kind: Service
metadata:
  name: route-engine
  labels:
    app: route-engine
  namespace: test
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "route-engine-test"
spec:
  selector:
    app: route-engine
  ports:
    - name: http-django-8001
      port: 80
      targetPort: 8001
  type: ClusterIP
