apiVersion: batch/v1
kind: Job
metadata:
  name: job-load-data
spec:
  template:
    spec:
      containers:
        - name: job-load
          image: ghcr.io/logicwayteam/logicway:001  # або образ із GHCR
          command: ["poetry", "run", "python", "manage.py", "loaddata", "initial_data.json"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
      restartPolicy: Never
  backoffLimit: 1
