apiVersion: batch/v1
kind: Job
metadata:
  name: job-load-data
spec:
  template:
    spec:
      containers:
        - name: job-load
          image: ghcr.io/logicwayteam/logicway:001
          env:
            - name: INTERNAL
              value: "1"
          command: [ "/bin/sh", "-c" ]
          args:
            - "poetry run python database/upload_data.py && poetry run python database/load_data.py"
      restartPolicy: Never
  backoffLimit: 1
