apiVersion: v1
kind: Service
metadata:
  name: logicway
spec:
  selector:
    app: logicway             # Має збігатися з labels у deployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer