apiVersion: apps/v1
kind: Deployment
metadata:
  name: route-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: route-engine
  template:
    metadata:
      labels:
        app: route-engine
    spec:
      containers:
        - name: route-engine
          image: ghcr.io/logicwayteam/logicway:001  # або ghcr.io/logicwayteam/route-engine:latest
          ports:
            - containerPort: 8001
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: route_engine.settings.prod
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: ROUTE_ENGINE_SECRET_KEY
