apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLW5tbGFjMmhAaSheLWlyeF9ibnRxKzglKCsqdmp6b3YrJUA5cmZ1c2Ird2d6cw==     # base64("django-secret-key")
  ROUTE_ENGINE_SECRET_KEY : ZGphbmdvLWluc2VjdXJlLWllaXJnNyZrLTJ5Mzc9ZV51MSg9KjQhdSMxKHBlQDh2JClicHQxJnpwX2s5KiQlYzNe
  DB_USER: cG9zdGdyZXM=                        # base64
  DB_PASSWORD: cG9zdGdyZXM=          # base64
