apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  namespace: test
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: traefik
  rules:
  - host: "logicway-test.taile241c6.ts.net"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /logicway(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: logicway
            port:
              number: 8000