{
 "title": "Logicway Service Dashboard",
 "time": { "from": "2025-06-05T20:11:20.682Z", "to": "2025-06-05T20:45:40.538Z" },
 "panels": [
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(django_http_responses_total_by_status_view_method_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{view!~\"<unnamed view>|prometheus-django-metrics\"}[5m])) by (le, view))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(django_http_responses_total_by_status_view_method_total{status=~\"5.*\"}[5m])) / sum(rate(django_http_responses_total_by_status_view_method_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}