apiVersion: v1
kind: Service
metadata:
  name: logicway
  labels:
    app: logicway
spec:
  selector:
    app: logicway
  ports:
    - name: http-django-8000
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
  type: NodePort
