apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: preprod
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "frontend-preprod"
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
