apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_NAME: "logicway"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  ROUTE_ENGINE_URL: "/route-engine"
  REACT_APP_LOGICWAY_URL: "/logicway"
  REACT_APP_ROUTE_ENGINE_URL: "/route-engine"
